### ISSUE TITLE
ParseException: Unmatched token at offset=20, when expected: Token(EOF)

### ISSUE THREAD

**Issue by asm0dey** [alllex/parsus#26] opened 2023-12-11 23:54 UTC
Given the following grammar:

```kotlin
    data class MappingEntry(val destinationStart: Long, val sourceStart: Long, val length: Long) {
        private val sourceRange: LongRange = sourceStart..(sourceStart + length)
        private val destinationRange: LongRange = destinationStart..(destinationStart + length)

        fun lookup(source: Long): Long? =
                if (source in sourceRange) destinationStart + (source - sourceStart) else null

        fun reverseLookup(destination: Long): Long? =
                if (destination in destinationRange) sourceStart + (destination - destinationStart) else null

    }

    data class Mapping(val entries: List<MappingEntry>) {
        fun lookup(source: Long): Long = entries.firstNotNullOfOrNull { it.lookup(source) } ?: source

        fun reverseLookup(destination: Long): Long =
                entries.firstNotNullOfOrNull { it.reverseLookup(destination) } ?: destination

    }

    val parser = object : Grammar<Pair<List<Long>, List<Mapping>>>(debugMode = true) {
        val num by regexToken("\\d+")
        val nl by literalToken("\n", "newline")
        val sp by regexToken(" +", "space")
        val colon by literalToken(":")
        val seedLit by literalToken("seeds")
        val toLit by literalToken("-to-")
        val mapLit by literalToken("map")
        val word by regexToken("[a-zA-Z]+")
        val range by num * -sp * num * -sp * num map {
            MappingEntry(it.t1.text.toLong(), it.t2.text.toLong(), it.t3.text.toLong())
        }
        val ranges by separated(range, nl)
        val mappingName by word * -toLit * word * -sp * -mapLit * -colon * -nl
        val mapping by -mappingName * ranges * -nl map { Mapping(it) }
        val mappings by separated(mapping, nl)
        val seeds by -seedLit * -colon * -sp * separated(num, sp) * -nl * -nl map { it.map { it.text.toLong() } }

        override val root by seeds * mappings map { it.t1 to it.t2 }
    }
```

and the following input:

```
seeds: 79 14 55 13

seed-to-soil map:
50 98 2
52 50 48

soil-to-fertilizer map:
0 15 37
37 52 2
39 0 15

fertilizer-to-water map:
49 53 8
0 11 42
42 0 7
57 7 4

water-to-light map:
88 18 7
18 25 70

light-to-temperature map:
45 77 23
81 45 19
68 64 13

temperature-to-humidity map:
0 69 1
1 0 69

humidity-to-location map:
60 56 37
56 93 4
```

I get the following exception:

```
Exception in thread "main" ParseException: Unmatched token at offset=20, when expected: Token(EOF)
	at me.alllex.parsus.parser.ParseResultKt.getOrThrow(ParseResult.kt:137)
	at me.alllex.parsus.parser.Grammar.parseOrThrow(Grammar.kt:73)
	at Day05Kt.main(Day05.kt:76)
	at Day05Kt.main(Day05.kt)
```
But the code and input seem legit. I would expect to see at least an expected token and the exact part of text with error

**Comment by alllex** [comment] 2023-12-19 00:07
Thank you for reporting an issue and providing a reproducer!

The grammar is non-trivial, so it took me a while to get to the bottom of the problem.
Turns out, the implementation of the `separated`.

It has a subtle bug that is only triggered when the separator for the list appears in the input after the list, but does not belong to it. Which is the case in your grammar with `nl` tokens.

I'll fix the implementation, and it is going to be shipped in the next release!

**Comment by asm0dey** [comment] 2023-12-19 05:53
Thank you for the investigation and spending time to debug it!

**Comment by alllex** [comment] 2023-12-19 14:35
This should be fixed in `v0.6.1` (just released). Could you try it out?

**Comment by asm0dey** [comment] 2023-12-19 14:45
Well, now the offset is different :)

```
Exception in thread "main" ParseException: Unmatched token at offset=296, when expected: Token(EOF)
```

**Comment by alllex** [comment] 2023-12-19 15:09
Could you try on a smaller example? For instance, only with two mappings?
```
seeds: 79 14 55 13

seed-to-soil map:
50 98 2
52 50 48

soil-to-fertilizer map:
0 15 37
37 52 2
39 0 15
```

If it still fails, could you check if adding or removing an extra newline at the end changes anything?

**Comment by asm0dey** [comment] 2023-12-19 15:13
Yes, adding a newline at the end does the trick! Is it an issue with my grammar?

**Comment by asm0dey** [comment] 2023-12-19 15:16
Yes, it's an issue with the grammar - mappings should be separated with `nl * nl` and then it works

**Comment by asm0dey** [comment] 2023-12-19 15:17
Thank you very much for your help!

**Closed** 2023-12-19 15:17 UTC

**Comment by asm0dey** [comment] 2023-12-19 15:29
JFYI, `register(regexToken("\\s+", ignored = true))` throws an exception; it should probably be just `regexToken("\\s+", ignored = true)`

**Comment by alllex** [comment] 2023-12-19 17:17
Ah, you are right, I forgot that `regexToken` call already does the registration 👍
